meteor npm install --save jquery
meteor npm install --save jszip
meteor npm install --save pdfmake
meteor npm install --save datatables.net-dt
meteor npm install --save datatables.net-editor-dt
meteor npm install --save datatables.net-autofill-dt
meteor npm install --save datatables.net-buttons-dt
meteor npm install --save datatables.net-colreorder-dt
meteor npm install --save datatables.net-keytable-dt
meteor npm install --save datatables.net-responsive-dt
meteor npm install --save datatables.net-rowgroup-dt
meteor npm install --save datatables.net-rowreorder-dt
meteor npm install --save datatables.net-scroller-dt
meteor npm install --save datatables.net-select-dt
